[tool.poetry]
name = "django-states3"
version = "2.0.0"
description = ""
authors = ["Mariusz Janczyn <mariusz@ulam.io>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
sphinx = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"